# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        python3 -m venv .venv I && source .venv/bin/activate
        python3 -m pip install --upgrade pip
        python3 -m pip install -r requirements.txt
        nohup python3 -m uvicorn app.main:app
        echo "Fim!"
